//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SibersTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsPriorities
    {
        public int id { get; set; }
    
        public virtual Priorities Priorities { get; set; }
        public virtual Projectss Projectss { get; set; }
    }
}
