//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SibersTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectsDBEntities : DbContext
    {
        public ProjectsDBEntities()
            : base("name=ProjectsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Leaders> Leaders { get; set; }
        public virtual DbSet<Performers> Performers { get; set; }
        public virtual DbSet<Priorities> Priorities { get; set; }
        public virtual DbSet<ProjectDates> ProjectDates { get; set; }
        public virtual DbSet<ProjectPerformers> ProjectPerformers { get; set; }
        public virtual DbSet<ProjectsInfoes> ProjectsInfoes { get; set; }
        public virtual DbSet<ProjectsPriorities> ProjectsPriorities { get; set; }
        public virtual DbSet<Projectss> Projectss { get; set; }
        public virtual DbSet<Projectsses> Projectsses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ProjectsInfo> ProjectsInfo { get; set; }
    }
}
