//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SibersTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsInfoes
    {
        public int id { get; set; }
        public int ProjectId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ProjectDateStart { get; set; }
        public System.DateTime ProjectDateEnd { get; set; }
        public int ProjectPriorityId { get; set; }
    }
}
